name: claude-code-dev
services:
  claude-code-dev:
    container_name: "claude-code-dev"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: [ "tail", "-f", "/dev/null" ]
    stdin_open: true
    tty: true
    volumes:
      # Claude configuration and credentials
      - ~/.claude.json:/home/node/.claude.json:delegated
      - ~/.claude:/home/node/.claude:delegated

      # SSH keys for Git operations
      - ~/.ssh:/home/node/.ssh:ro

      # Gradle cache to speed up builds
      - ~/.gradle:/home/node/.gradle:delegated

      # IntelliJ cached resources to speed up container startup on rebuild and retain installed plugins
      - ~/Dev/.devcontainer/.cache/intellij/idea-IU-251.26094.121:/home/node/.cache/JetBrains/RemoteDev/dist/idea-IU-251.26094.121:delegated
      - ~/Dev/.devcontainer/.cache/intellij/remote-plugins:/.jbdevcontainer/JetBrains/IntelliJIdea2025.1/plugins:delegated
      - ~/Dev/.devcontainer/.cache/intellij/plugin-data:/.jbdevcontainer/data/JetBrains/IntelliJIdea2025.1:delegated
      - ~/Dev/.devcontainer/.cache/intellij/idea-config:/home/node/.config/JetBrains/RemoteDev-IU:delegated
      - ~/Dev/.devcontainer/.cache/intellij/user-plugins:/home/node/.cache/JetBrains/RemoteDev/dist/idea-IU-251.26094.121/plugins:delegated

      # Primary workspace mount
      - ..:/workspace
